import { expect, it, vi } from 'vitest';
import { createReactionTools } from './reaction-tools';
import type { ReactionStore } from './reaction-store';

it('binds reaction identity and checks private-human publication authority on every call', async () => {
  const store = { set: vi.fn(async () => []), read: vi.fn(async () => ({ message: [] })), recent: vi.fn(async () => ['👩🏽‍💻']) }, changed = vi.fn();
  let human = false;
  const tools = createReactionTools(store as unknown as ReactionStore, { id: 'private', agentId: 'a', kind: 'platform-chat' }, () => human, changed);
  const call = (name: string, args: object, signal?: AbortSignal) => tools.find(tool => tool.name === name)!.execute('call', args as never, signal, undefined, undefined as never);
  await expect(call('react_to_message', { channelId: 'private', messageId: 'message', emoji: '👍', active: true })).rejects.toThrow('not granted');
  human = true;
  const reacted = await call('react_to_message', { agentId: 'spoofed', channelId: 'private', messageId: 'message', emoji: '👍', active: true });
  const receipt = reacted.content[0];
  if (receipt.type !== 'text') throw new Error('Expected text reaction receipt');
  expect(JSON.parse(receipt.text).recent).toEqual([{ emoji: '👩🏽‍💻', label: 'woman technologist: medium skin tone' }]);
  expect(store.set).toHaveBeenCalledWith('private', 'message', '👍', true, 'a');
  expect(changed).toHaveBeenCalledWith('private', 'message');
  await call('read_reactions', { channelId: 'group:g', messageId: 'message' });
  expect(store.read).toHaveBeenCalledWith('group:g', ['message'], 'a');
  const found = await call('search_emojis', { query: 'coder', limit: 20 });
  const entry = found.content[0];
  if (entry.type !== 'text') throw new Error('Expected text search results');
  const output = JSON.parse(entry.text);
  expect(output.recent).toEqual([{ emoji: '👩🏽‍💻', label: 'woman technologist: medium skin tone' }]);
  expect(output.matches.some((item: { emoji: string }) => item.emoji === '👩🏽‍💻')).toBe(true);
  expect(store.recent).toHaveBeenCalledWith('a');
  const controller = new AbortController(); controller.abort();
  await expect(call('react_to_message', { channelId: 'group:g', messageId: 'message', emoji: '👍', active: true }, controller.signal)).rejects.toThrow();
  expect(store.set).toHaveBeenCalledTimes(1);
});
