import type { KnowledgeEntry } from '../catalog';
export const computerFiles = {
  id: 'swarm/computers/files', parentId: 'swarm/computers', title: 'Guest files and synchronous commands',
  summary: 'read/edit/write/bash on the currently claimed computer: paths, bounds, cancellation and image reading.',
  source: 'docs/agent-computer-use.md',
  content: `These custom tools act only in the computer you currently hold through use_computer. Assignment alone is insufficient; every call rechecks assignment and control. There is no platform-host filesystem/shell access and no transfer of provider/developer credentials. Another agent's claim cannot be bypassed by supplying a computer ID or path. Release/revocation cancels and settles outstanding operations before transfer; uncertain settlement keeps the claim held.

Paths are guest absolute paths, ~/ under /home/agent, or relative to /workspace. Bash cwd also defaults to /workspace and may be explicitly set; cd/environment changes do NOT persist to another call. Work runs as the guest agent account with a minimal environment and its existing permissions, including configured sudo. This is broad access to that computer, not a restricted-path sandbox. Do not seek platform-host files or credentials.

read({path,offset?,limit?}) returns UTF-8 text, up to 2000 lines/50000 bytes. Offsets are 1-based. Use nextOffset to continue; partial long lines have no line continuation and require a bounded bash extraction. Invalid UTF-8 bytes are replaced for viewing; editing requires valid UTF-8. Regular files only. PNG/JPEG/GIF/WebP/BMP are returned as real model images (first frame, <=4096 pixels/axis,16 million pixels,2MiB output). Larger images need guest-side resizing/conversion; text-only models cannot receive them. File image copies use the shared 50MB image pool and may expire. They are NOT desktop screenshots and do not grant action allowance.

write({path,content}) creates parents and atomically replaces one UTF-8 file. Existing file modes are retained; new files are private. edit({path,edits:[{oldText,newText}]}) requires 1–100 unique, nonoverlapping exact matches against the ORIGINAL file, validates all before committing, and rejects detected concurrent changes. Read again after a stale/ambiguous match instead of guessing. It is optimistic, not a filesystem-wide lock against human editors. Edit target/result <=16MiB; each tool request <=64KiB, including all text/JSON overhead.

bash({command,cwd?,timeout?}) is synchronous, default30 seconds/max120. It returns exitCode and separate stdout/stderr tails, each <=25000 bytes/1000 lines, with truncation flags. Use bounded searches/extractions or redirect necessary output to an ordinary guest file then read it. There is no background process-management API or persistent shell. Do not use nohup, setsid, service/daemon launch, or other detachment to evade the synchronous lifetime. The worker has a private PID/mount namespace (ps and /proc show that command's processes, not the existing desktop processes); normal worker exit kills its descendants, even detached ones. No new host privileges or mounts are granted. Cancellation cannot undo writes, network requests, or work already submitted to external services; inspect effects before retrying. Privileged guest tampering is not sandboxed. A lost supervisor leaves control blocked until a human resolves it, potentially by restarting the computer; agents must not claim cleanup succeeded without a receipt.

Core calls require a claim but no screenshot. They never renew the GUI two-combo/30-second allowance. bash/write/edit invalidate that allowance, so take a fresh glance/look_at before run_actions. A nonzero exit or partial error is not task success; inspect the actual result, do not blindly repeat side effects. Release with use_computer({computer:null}) when finished unless asked to keep the computer dedicated.`,
} satisfies KnowledgeEntry;
