CREATE TABLE "SwarmSettings" (
  "id" INTEGER NOT NULL PRIMARY KEY DEFAULT 1,
  "maxComputers" INTEGER NOT NULL DEFAULT 4,
  "uploadMaxMb" INTEGER NOT NULL DEFAULT 100,
  "scratchFileMaxKb" INTEGER NOT NULL DEFAULT 1024,
  "scratchMaxFiles" INTEGER NOT NULL DEFAULT 500,
  "scratchTotalMb" INTEGER NOT NULL DEFAULT 50,
  "storageBudgetGb" INTEGER NOT NULL DEFAULT 10,
  "updatedAt" DATETIME NOT NULL
);
